language: swift
osx_image: xcode11.2
xcode_project: Static.xcodeproj

env:
   global:
     - SCHEME="Static-iOS"
     - IOS_SDK=iphonesimulator13.2
   
jobs:
  include:
    - stage: unit tests
      name: iPhone X
      env: DESTINATION="OS=12.2,name=iPhone X" SDK="$IOS_SDK"
      script: 
        - xcodebuild -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" test
        
    - stage: SPM
      name: SPM tests
      script:
        - swift test -c debug

stages:
  - unit tests
  - SPM
